version = "1.0"

[main]
name.en = "Rspamd Web UI configuration"
services = ["__APP__"]

    [main.customization]

        [main.customization.password]
        ask.en = "Set a new password for the Rspamd web interface access"
        type = "password"
