packaging_format = 2

id = "rspamdui"
name = "Rspamd Web UI"
description.en = "Simple control interface for rspamd spam filtering system"
description.fr = "Interface de contrôle simple pour le système de filtrage de spam rspamd"

version = "1.0~ynh3"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://rspamd.com/webui"
code = "https://github.com/rspamd/rspamd"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/rspamd"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
