test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    #preinstall = "sudo systemctl enable rspamd --now"

    preinstall = """
    sudo yunohost app install https://github.com/YunoHost-Apps/rspamd_ynh
    sudo systemctl enable rspamd --now"
    """

