#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__password() {
    echo ""
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
    if [ ! "$password" == "" ]
    then
        ynh_print_info --message="Saving the new password $password in the Rspamd configuration..."
        HASH=$(rspamadm pw -p "$password")
        echo "password = \"$HASH\"" > /etc/rspamd/local.d/worker-controller.inc
    fi
}

#=================================================
ynh_app_config_run "$1"
