#!/bin/bash

domain=$(sudo yunohost app setting rspamdui domain)

sudo rm /etc/nginx/conf.d/$domain.d/rspamdui.conf
sudo service nginx reload
sudo yunohost app ssowatconf                                                                                                                                                                     
