#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# SPECIFIC REMOVE
#=================================================
# CONFIGURE RSPAMD
#=================================================
ynh_script_progression "Configuring RSPAMD..."

ynh_replace_regex --match="^password = .*" --replace="password = \"q1\";" --file=/etc/rspamd/worker-controller.inc

ynh_systemctl --service=rspamd --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
